apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: web-mirror-vs
spec:
  hosts:
  - web-service.default.svc.cluster.local
  http:
  - route:
    - destination:
        host: web-service.default.svc.cluster.local
        subset: v1
      weight: 100
    mirror:
      host: web-service.default.svc.cluster.local
      subset: v2
    mirror_percent: 100

