apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: web-virtualservice
spec:
  hosts:
  - web-service.default.svc.cluster.local
  http:
  - route:
    - destination:
        host: web-service.default.svc.cluster.local
        subset: v1
      weight: 25
    - destination:
        host: web-service.default.svc.cluster.local
        subset: v2
      weight: 75